# Config file for automatic testing at travis-ci.org

language: python
python:
  - 2.7
  - 3.6
matrix:
  allow_failures:
  - python: 3.6
install:
  - pip install -r dev_requirements.txt
cache: pip
script:
  - py.test